# Generated by Django 2.0.5 on 2018-06-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('idd', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('privacy', models.CharField(max_length=100)),
                ('admin', models.CharField(max_length=200)),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('mname', models.CharField(max_length=200)),
                ('midd', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('memail', models.TextField()),
                ('madmin', models.BooleanField()),
                ('mgroup', models.CharField(max_length=200)),
            ],
        ),
    ]
